src/FlipMove.js, test/index.spec.js
TransitionEnd event listeners not removed automatically, after domNodes reordering, u can check it with this code:
```javascript
import React, {Component} from 'react';
import ReactDom from 'react-dom';
import FlipMove from 'react-flip-move';
import _ from 'lodash'
class Main extends Component{
constructor(props){
super(props);
this.state = {
arr:_.range(3)
};
this.count = 0;
}
shuffle(){
this.setState({arr:this.state.arr.reverse()})
}
start(){
console.log('start');
}
finish(){
this.count++;
console.log(this.count);
}
render(){
let {arr} = this.state;
let style = {fontSize:'34px', background:'silver', border:'1px solid black'};
return (<div className="container">
<FlipMove
duration={500}
onFinish={::this.finish}
onStart={::this.start}
>
{arr.map((i,key)=> {
return (<div key={i} …
```
=> Remove transitionEnd event listener after animation end

src/FlipMove.js
A bug was causing children to not be updated when
`disableAllAnimations` was set to true. This hotfix addresses this
concern, and also disables the calculation when the user's browser
does not support CSS transitions.
=> Ensure children are always updated

README.md, src/FlipMove.js, src/prop-converter.js, stories/index.js
See https://github.com/joshwcomeau/react-flip-move/pull/59
Hope the squash button shows up now... It doesn't on my side :P
I read all the docs. It should really show up when you are about to merge it. They either removed the feature or disabled it for some reason. I don't see it on my own repo's either.
Let me know if I need to squash it; i'll update the PR.
=> Add new prop `getPosition()` (attempt 2)

src/dom-manipulation.js
A change in the latest version is causing server rendering (or testing, in my case) to fail because of `HTMLElement` being undefined.
Added a simple check for that.
=> Prevent error with HTMLElement when not redering from browser

README.md
I liked this custom animation a lot, but found that it caused weird 'hangs' at the beginning and end of animations when sorting multiple items per transition. By making these changes, the transitions are greatly smoothed out and much more pleasing to the eye. I also changed the format just a little so that its more common usage pattern is a little more obvious.
=> minor change to example custom animation in readme

src/FlipMove.js
I was hitting a case where I had a child in the props' children, that did not have any data in the childrenData. I was having trouble tracking down how it got into that state. I have multiple nested flipmove instances, so that might have something to do with it. I thought I'd try just preventing it from blowing up and everything seemed to work correctly afterwards.
The error was occurring in getRelativeBoundingBox, when childData was undefined.
=> Fix case where there is no childrenData for a child prop

src/FlipMove.js
These two commits fix the following issues:
1) `this.childrenToAnimate` is only reset if you have a `onFinishAll` hook, which makes the list grow forever if you don't define one.
2) Children that have been animated away are still referenced by `this.childrenData`, preventing the browser from garbage collecting them.
=> Remove references to nodes that have left

src/FlipMove.js
If animation is disabled, allow the children to update from the new props.
I am turning animation off for a few different user actions. While it is turned off, any changes to the children are rendered one prop change behind. A forceUpdate triggers it to get up to date.
For example, with animation disabled:
Start with children A, B;
Add child C;
FlipMove will still show A, B;
Add child D;
FlipMove will now show A, B, C;
I think this also resolves pull request 91.
=> When not animating, allow the children to update.

src/helpers.js, src/prop-converter.js
This commit should fix issue #99 since `React.Children.toArray` already take care of "corner cases".
=> Allows to have no children (fix #99)

README.md
Noticed that the table of contents will navigate away from [npmjs.com/package/react-flip-move](npmjs.com/package/react-flip-move) because the href URLs are absolute.
Also converted a couple of HTML tags to markdown.
=> Relative TOC links

package.json, src/prop-converter.js
Hi Joshua! We've been loving this module thanks for sharing it! I'm doing a bit of bundle analysis of our app and noticed that this included lodash.omit which, as it turns out, also has several sub dependencies and ends up adding a surprising (at least to me) 6.5kb to the gzipped/minified size by my measurements. 
Given that `omit` is fairly simple in concept, I thought it'd may be worthwhile to inline a little `omit` implementation and send it your way for feedback.
Thanks again for this slick module!
=> removed lodash.omit dependency which shaves off ~6.5kb of min+gzip size

src/FlipMove.js, src/helpers.js, src/polyfills.js, stories/enter-leave-animations.stories.js, stories/helpers/FlipMoveWrapper.js
Right now, if you try to change some component inside FlipMove while animation is running, it will cause a weird animation as stated in "Known Issues"
This happen because when component inside FilpMove changes, it will try to re-calculate animating components in `runAnimation` method again via `componentDidUpdate` and store into `remainingAnimations`. And if animation is already running, it will doubled up `remainingAnimations` count.
I workaround that by instead of comparing children in each prop directly, I compare children key equality. So if the children is the same set, FlipMove should not rerun animation.
=> Fix weird animation when inside component get change by set while animating

src/FlipMove.js, src/prop-converter.js
Prop converter does several runtime checks and logs warnings that aren't needed in production.  When `process.env.NODE_ENV === 'production'`, they are now disabled.
=> Suppress warnings when in production

src/FlipMove.js, src/prop-converter.js
Per the react spec, `props.children` should be treated as an opaque object, not an array.  The `React.Children` api should be used to handle this object.
The current implementation was working fine with regular react, but these changes are necessary for compatibility with substitutes like preact.
=> Remove direct usage of opaque children object

src/error-messages.js, src/prop-converter.js
While working on #153, I've noticed then when preact children are supplied, they generate false positive warnings about them being SFC. This is not a really big issue, but, to stop spoiling the console, I've added some deduplication, so that each type of warning fires only once
=> Deduplicate warnings

package.json
As @AlexanderOtavka has [pointed out](https://github.com/joshwcomeau/react-flip-move/pull/151#discussion_r116388826), `preact` is a peer dep of `preact-compact`. In fact, storybook-preact doesn't run without it:
```
ERROR in ./~/preact-compat/dist/preact-compat.js
Module not found: Error: Cannot resolve module 'preact' in /Users/jetbrains/react-flip-move/node_modules/preact-compat/dist
```
=> Hotfix: satisfy preact peerDependency to make storybook run

README.md, flow-typed/react-flip-move_v2.9.x.js, package.json, src/typings.js, yarn.lock
Should partially fix #157. The `react-flip-move_v2.9.x.js` file is exactly the same as the one commited in https://github.com/flowtype/flow-typed/pull/844, and they have to stay in sync. Ideally they shouldn't be touched though, unless a minor version comes and brings some new API
=> Extract public API typings into libdef

tslint.json, typings/react-flip-move.d.ts, typings/test.tsx
Version 2.9.13 completely broke react-flip-move for me as a TypeScript user. I'm not fully versed in how the different module/bundling systems work, but it seems that the included bindings exported the type definitions in a way that wasn't aligned with how the component is actually exported. The included test TypeScript file compiled ok, but once you tried to use the component in a TypeScript application, everything blew up at runtime.
Using the [export =](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) method in the type definitions fixes these problems. This PR is based on the [@types/react-flip-move package's typings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-flip-move) with a few additional fixes (the addition of …
=> Fix TypeScript typings

src/FlipMove.js, src/dom-manipulation.js, stories/github-issues.stories.js
Adressing https://github.com/joshwcomeau/react-flip-move/issues/120
So after spending some time tracking down the issue demonstrated in https://github.com/joshwcomeau/react-flip-move/pull/180/files#diff-5bc397e1b32daa8794012a8ea12ce91aR17 (based off of @ConneXNL work  ❤️ ), i found that upon deletion of the childData entry, state is not updated. this means no rerender is triggered, and when a rerender is eventually triggered, we still have a child without corresponding childData (i.e. a zombie).
i've console.logged the lifecycle of such an element in this commit: https://github.com/joshwcomeau/react-flip-move/pull/180/commits/7f6f5972a9141e9c29b2fd5bdbe137bcb2bcf49a
the fix implemented here updates state in the `removeChildData` call. this seems to be working fine, but i'd appreciate some …
=> Fix Issue120

test/index.spec.js
See https://github.com/joshwcomeau/react-flip-move/issues/162#issuecomment-313849035
=> Increase CI tests stability by replacing window.requestAnimationFrame

flow-typed/react-flip-move_v2.9.x.js, src/FlipMove.js, src/error-messages.js, src/prop-converter.js, src/typings.js, test/index.spec.js
This is a follow-up to #183 
It turned out that the way I used react types in libdef file leads to all of them coercing to `any` (see https://github.com/flowtype/flow-typed/issues/1209#issuecomment-326756417)
This PR fixes that, plus restricts children types to react elements, and items filtered out by `Children.toArray` (those include `undefined`, `null`, and booleans)
I also made a PR to `flow-typed` with new libdef, so that it's available for external usage: https://github.com/flowtype/flow-typed/pull/1210
=> Fix weak types in libdef

src/dom-manipulation.js
getNativeNode checks if element is instanceOf HTMLEment, which doesn't work if the FlipMove component is rendered inside an iFrame using React Portal.
Changed getNativeNode to check absolutely if node is a text node.
This is a resubmission, stopped jsprettier from polluting file and added type refinement to satisfy flow.
=> do absolute check for node type

src/FlipMove.js
The `props` property doesn't seem to be initialized at this point when creating a <FlipMove> component, which leads to an error.
=> Fix on IE10

src/FlipMove.js, src/error-messages.js, stories/misc.stories.js
Quick update to enforce a non-static position on the parent container in wrapperless mode. Issues a warning so that the user knows what's up.
=> Add position: relative to static parents in wrapperless mode

documentation/api_reference.md, typings/react-flip-move.d.ts
In readme it is mentioned that typeName accepts `null`. Previous typings did not allow to use it.
Also, there was a typo in documentation concerning typeName. Previously it was rendered like `null` was a default value.
=> Fix typescript typings and documentation section of typeName prop

src/FlipMove.js
In my project I have faced performance issues: it took about 700ms to process animations for a list with 30 elements. I noticed styles recalculations took the biggest part of it.
It was mentioned (e.g. [here](http://gent.ilcore.com/2011/03/how-not-to-trigger-layout-in-webkit.html)) that DOM calculated sizes functions should be used with caution. To achieve highest performance reads and writes should be performed in batches.
After applying some changes time to rerender the list reduced by 4 times.
=> Increasing performance by avoiding styles recalculations

package.json, src/FlipMove.js, src/error-messages.js, test/index.spec.js, yarn.lock
In Internet Explorer 11 (and below), the `transitonend` event will not (consistently) fire for elements that have the `disabled` attribute. This means the callback for node removal is never fired and the supposedly removed nodes stay in the html.
This PR adds a new warning to inform about this quirk. Before a node is removed, the list children are checked for `disabled`. If one or more are found and animations are not disabled, the warning emits.
ps.: this also takes care of the cleanup issue i mentioned [here](https://github.com/joshwcomeau/react-flip-move/issues/209#issuecomment-354853118)
=> Warn if children are disabled

src/enter-leave-presets.js, src/error-messages.js, src/prop-converter.js, test/index.spec.js
That lands us at **4905** - and actually this includes UMD wrapper (because I test `dist/react-flip-move.min.js`), so the actual size in apps will be slightly smaller
=> Removed deprecated options

README.md
On [Spectrum](https://spectrum.chat/thread/df65e157-d118-40cd-87c8-88bdd3724aa1), the first comment was about how the [Flip Move blog post](https://medium.com/developers-writing/animating-the-unanimatable-1346a5aab3cd) was cool, but hard to find, since I use the same link text earlier for the [Aerotwist post](https://aerotwist.com/blog/flip-your-animations/#the-general-approach) that inspired this project.
This quick fix gives the blog post its own little paragraph. I also tweaked the final bullet-point to be more to-the-point (and to correct the slight lie that it was under 6kb, although with #213 we may soon be able to brag that it's under 4kb!).
I didn't tag any reviewers because I don't want to impose on anyone's time for a copy change, but if anyone has any suggestions about this, …
=> Make link to blog post more prominent.

.storybook/.babelrc
When running React Storybook locally, I was getting the following error:
```
ERROR in ./.storybook/config.js
Module build failed: Error: Couldn't find preset "./.babelrc.js" relative to directory "/Users/joshu/work/flip-move/.storybook"
```
This is easy enough to understand; our `.babelrc` file now looks like this:
```json
{
"presets": ["./.babelrc.js"]
}
```
It appears that for some reason, Storybook config is trying to load this relative to the storybook dir, and failing to find it there.
I tried creating a new `.babelrc` file inside `.storybook`, and simply pointing it to `../.babelrc.js`, but then it fails with a similar error, trying to open it from a subdirectory:
```
ERROR in ./stories/helpers/FlipMoveListItem.js
Module build failed: Error: Couldn't find preset "../.babelrc.js" …
```
=> Add babelrc for storybook

typings/react-flip-move.d.ts, typings/test.tsx
This should fix react-flip-move for TypeScript users. Replaces #220.
=> Fix TypeScript export type

typings/react-flip-move.d.ts
Hi!
`@types/react` has been updated for react 18 to no longer include an implicit `children` prop on every `Component`. This means `<FlipMove>` is no longer usable with the latest react typings because you must pass `children` to `<FlipMove>` but TypeScript thinks the `<FlipMove>` component doesn't accept any `children`.
This PR adds an explicit `children` prop to the typings including a doc comment.
Thanks!
=> Add explicit children prop
